name: Deploy a prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH

        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
          APP_PORT: ${{ secrets.APP_PORT }}

        run: |
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$SSH_HOST << EOF
            set -e
            cd $REMOTE_PATH

            echo "📥 Haciendo pull del código..."
            git checkout main
            git pull origin main

            APP_PORT=$APP_PORT docker-compose up -d --build
          EOF
